### PR TITLE
Add hardware acceleration support for aes.

### PR DESCRIPTION
**Pull request by sladyn98**
This PR will be for adding hardware accleration support for btls

### CODE REVIEW

**Comment by sladyn98** [comment]
@nealef Kindly have a look :)

**Comment by nealef** [comment]
Something more like this:
```
--- a/crypto/fipsmodule/des/internal.h
+++ b/crypto/fipsmodule/des/internal.h
@@ -65,6 +65,67 @@
 extern "C" {
 #endif
 
+#if !defined(OPENSSL_NO_ASM)
+
+#if defined(OPENSSL_S390X)
+#define HWDES
+
+OPENSSL_INLINE int hwdes_capable(void) {
+  return (some routine you have defined in cpu_s390x.c)
+}
+
+#if defined(HWDES)
+
+int des_hw_set_encrypt_key(const uint8_t *user_key, const int bits,
+                           DES_KEY *key);
+int des_hw_set_decrypt_key(const uint8_t *user_key, const int bits,
+                           DES_KEY *key);
+void des_hw_encrypt(const uint8_t *in, uint8_t *out, const DES_KEY *key);
+void des_hw_decrypt(const uint8_t *in, uint8_t *out, const DES_KEY *key);
+void des_hw_cbc_encrypt(const uint8_t *in, uint8_t *out, size_t length,
+                        const DES_KEY *key, uint8_t *ivec, const int enc);
+void des_hw_ctr32_encrypt_blocks(const uint8_t *in, uint8_t *out, size_t len,
+                                 const DES_KEY *key, const uint8_t ivec[16]);
+
+#else
+
+// If HWDES isn't defined then we provide dummy functions for each of the hwdes
+// functions.
+OPENSSL_INLINE int hwdes_capable(void) { return 0; }
+
+OPENSSL_INLINE int des_hw_set_encrypt_key(const uint8_t *user_key, int bits,
+                                          DES_KEY *key) {
+  abort();
+}
+
+OPENSSL_INLINE int des_hw_set_decrypt_key(const uint8_t *user_key, int bits,
+                                          DES_KEY *key) {
+  abort();
+}
+
+OPENSSL_INLINE void des_hw_encrypt(const uint8_t *in, uint8_t *out,
+                                   const DES_KEY *key) {
+  abort();
+}
+
+OPENSSL_INLINE void des_hw_decrypt(const uint8_t *in, uint8_t *out,
+                                   const DES_KEY *key) {
+  abort();
+}
+
+OPENSSL_INLINE void des_hw_cbc_encrypt(const uint8_t *in, uint8_t *out,
+                                       size_t length, const DES_KEY *key,
+                                       uint8_t *ivec, int enc) {
+  abort();
+}
+
+OPENSSL_INLINE void des_hw_ctr32_encrypt_blocks(const uint8_t *in, uint8_t *out,
+                                                size_t len, const DES_KEY *key,
+                                                const uint8_t ivec[16]) {
+  abort();
+}
+
+#endif  // !HWDES
 
 #define c2l(c, l)                         \
   do {
```
You will create a file ```./crypto/cpu_s390x.c``` that will house the capability check.

**Comment by nealef** [comment]
Looks okay but I am not sure there is going to be des_hw_ctr32_... functions. I don't believe des has ctr type ciphers. AES has CTR and CBC. DES only has CBC although BTLS does define a ncbc_ function which libica also has. So I suspect you're going to have to define des_hw_ncbc  stuff as well.

**Comment by sladyn98** [comment]
@nealef Kindly have a look at the `aes_cbc` lookup.

**Comment by nealef** [comment]
* ```is_s390x_capable()``` needs to return true if the dlopen works. 
* Note, the prototype of ```ica_aes_cbc()``` is as follows:
```
ICA_EXPORT
unsigned int ica_aes_cbc(const unsigned char *in_data, unsigned char *out_data,
                         unsigned long data_length, unsigned char *key,
                         unsigned int key_length, unsigned char *iv,
                         unsigned int direction);
```
Therefore, the code in btls needs to reflect this.
```
unsigned int (*ica_aes_cbc)(const unsigned char *in_data, unsigned char *out_data,
                         unsigned long data_length, unsigned char *key,
                         unsigned int key_length, unsigned char *iv,
                         unsigned int direction);
```
You then need to see what parameters btls passes to its aes_hw_[en|de]crypt() API and then map them to the parameters you will pass in the call to the libica function. For example, the btls aes_hw_cbc_encrypt() function is defined:
```
OPENSSL_INLINE void aes_hw_cbc_encrypt(const uint8_t *in, uint8_t *out,
                                       size_t length, const AES_KEY *key,
                                       uint8_t *ivec, int enc)
```
Mapping parameters:
1. in -> in_data
2. out -> out_data
3. length -> data_length
4. key.rd_key -> key
5. ivec -> iv
6. enc -> direction

The key length is determined by what aes algorithm will use. This is available in AES_KEY which is defined as:
```
struct aes_key_st {
  uint32_t rd_key[4 * (AES_MAXNR + 1)];
  unsigned rounds;
};
```
When you implement ```aes_hw_set_[de|en]crypt_key()``` you will be passed the following:
```
OPENSSL_EXPORT int AES_set_encrypt_key(const uint8_t *key, unsigned bits,
                                       AES_KEY *aeskey);
```
The bits value defines the key length. So you can simply store the bits value in the rounds member. Then the ```aes_hw_cbc_encrypt()``` function will be able to pick up the value of ```key_length```.
```
int AES_set_decrypt_key(const uint8_t *key, unsigned bits, AES_KEY *aeskey)
{
    aeskey->rounds = bits/8;
    memcpy(aeskey->rd_key, bits/8, key);
}
```
I probably have the details wrong but this is the general idea.

**Comment by sladyn98** [comment]
@nealef Kidnly review the aes_hw_encrypt function

**Comment by nealef** [comment]
* Check indentation
* Cast return of ica_aes_ecb to (void) to avoid compiler warning

**Comment by nealef** [comment]
Check indentation and now add the _ecb_ encrypt/decrypt stuff.

**Comment by sladyn98** [comment]
@nealef Added the `ctr32_encrypt_blocks` function. Kindly review.

**Comment by nealef** [comment]
You need to do research on this call. You need to map the parameters to this function to the parameters you use to call the ica function.
```
void aes_hw_ctr32_encrypt_blocks(const uint8_t *in, uint8_t *out, size_t len,
                                 const AES_KEY *key, const uint8_t ivec[16])

(void) ica_aes_ctr(in_data, out_data,  data_length,aes->rd_key, key_length, *ctr, ctr_width,
			 ICA_ENCRYPT);
```
At first glance:
1. in_data -> in
2. out_data -> out

Where are you getting key_length, ctr, and ctr_width from? How does ivec fit in?

**Review by nealef — APPROVED** [review]

**Pull request merged**
